development:
  adapter: postgresql
  encoding: unicode
  database: pumk_development
  pool: 5
  username: budwhite
  password:

#test:
  #adapter: sqlite3
  #database: db/test.sqlite3
  #pool: 5
  #timeout: 5000
